---
abstract: "Bindings for the CloudStack API\r"
author:
  - 'Shugo Numano <numano@cc.rim.or.jp>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-CloudStack
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Digest::SHA: 0
  Encode: 0
  HTTP::Response: 0
  JSON: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Mouse: 0
  Mouse::Util::TypeConstraints: 0
  Test::More: 0
  URI::Encode: 0
  XML::Simple: 0
  XML::Twig: 0
version: 0.00014
