--- #YAML:1.0
name:               Net-CloudStack
version:            0.00003
abstract:           Bindings for the CloudStack API
author:
    - Shugo Numano <numano@cc.rim.or.jp>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Digest::SHA:          0
    Encode:               0
    JSON:                 0
    MIME::Base64:         0
    Moose:                0
    Moose::Util::TypeConstraints:  0
    Test::More:           0
    URI::Encode:          0
    WWW::Mechanize:       0
    XML::Twig:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
